import 'package:flutter/material.dart';
import 'package:flutter_logical_quiz/utility/app_extensions.dart';

Color alphaColor = "#FFFAE1".toColor();
Color primaryColor = "#35358d".toColor();
// Color subColor = "#379F64".toColor();
Color subColor = "#35358d".toColor();
Color subPrimaryColor = "#379F64".toColor();
Color textColor = "#000000".toColor();
Color subTextColor = "#666666".toColor();
Color subDarkTextColor = "#B3B3B3".toColor();
Color cellColor = "#F1F1F1".toColor();
Color darkCellColor = "#303030".toColor();
Color subBgColor = '#D4F0DF'.toColor();
Color subDarkBgColor = "#303030".toColor();
Color appBackgroundColor = "#FFFFFF".toColor();
Color darkBackgroundColor = "#000000".toColor();
Color cardColor = "#FFFFFF".toColor();
Color darkCardColor = "#181818".toColor();
Color greenColor = "#43C577".toColor();
Color skipColor = "#FFDF39".toColor();
Color redColor = "#E53A35".toColor();
Color dialogColor = "#292929".toColor();
