// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA455inva2nQUhRttPLJPOdY945lfAe8dw',
    appId: '1:909106559073:web:87a07630dfbdac340f9220',
    messagingSenderId: '909106559073',
    projectId: 'quiz-app-with-firebase-3d3d8',
    authDomain: 'quiz-app-with-firebase-3d3d8.firebaseapp.com',
    databaseURL: 'https://quiz-app-with-firebase-3d3d8-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-with-firebase-3d3d8.appspot.com',
    measurementId: 'G-G0ZB93XL2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv9rLebaXHGCLtEr4g6ceuh8RDDyD8l2M',
    appId: '1:909106559073:android:26f6ec3e83562a350f9220',
    messagingSenderId: '909106559073',
    projectId: 'quiz-app-with-firebase-3d3d8',
    databaseURL: 'https://quiz-app-with-firebase-3d3d8-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-with-firebase-3d3d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhYsU5teImNbSiUyPZynUEyxJ38O6zAs',
    appId: '1:909106559073:ios:4ab00900575614700f9220',
    messagingSenderId: '909106559073',
    projectId: 'quiz-app-with-firebase-3d3d8',
    databaseURL: 'https://quiz-app-with-firebase-3d3d8-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-with-firebase-3d3d8.appspot.com',
    iosBundleId: 'com.example.flutterLogicalQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdhYsU5teImNbSiUyPZynUEyxJ38O6zAs',
    appId: '1:909106559073:ios:0565c575c6caa3be0f9220',
    messagingSenderId: '909106559073',
    projectId: 'quiz-app-with-firebase-3d3d8',
    databaseURL: 'https://quiz-app-with-firebase-3d3d8-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-with-firebase-3d3d8.appspot.com',
    iosBundleId: 'com.example.flutterLogicalQuiz.RunnerTests',
  );
}
